#!/usr/bin/env bash

# Simple script to generate Packages.gz file from ipk files
#
# Copyright (C) 2012 Nick Glynn <Nick.Glynn@feabhas.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, version 2.
# 


rm Packages.gz Packages >/dev/null 2>&1
for i in `ls *.ipk` ;
do
	echo "Parsing $i"
	ar -vx "$i" control.tar.gz >/dev/null 2>&1
	tar zxvf control.tar.gz ./control >/dev/null 2>&1
	
	if [ -f control ]
	then
		cat control >> Packages
		echo -e "" >> Packages

		rm control
		rm control.tar.gz
	fi
done

gzip -9c Packages > Packages.gz
