#!/bin/sh -e

# Simple script to generate Packages.gz file from ipk files
#
# Copyright (C) 2013 Nick Glynn <Nick.Glynn@feabhas.com>
# Copyright (C) 2016 Jan Sarenik <jan.sarenik@jasan.tk>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, version 2.
# 

> Packages

for i in *.ipk
do
	echo "Parsing $i" >&2
	ar -p "$i" control.tar.gz | tar zxO ./control >> Packages
	
	size=$(stat --printf=%s "$i")
	md5=$(md5sum "$i" | cut -b-32)
	sha256=$(sha256sum "$i" | cut -b-64)

	{
		echo "Size: $size"
		echo "Filename: $i"
		echo "MD5sum: $md5"
		echo "SHA256sum: $sha256"
		echo
	} >> Packages
done

test -s Packages && gzip -9c Packages > Packages.gz
